import Foundation

extension OntologyCompiler {
    func emit(ir: JSONObject, to outDirectory: String) throws {
        let outURL = URL(fileURLWithPath: outDirectory)
        try FileManager.default.createDirectory(at: outURL, withIntermediateDirectories: true)
        try write(json: ir, to: outURL.appendingPathComponent("ontology.normalized.json"))
        try write(text: emitRefs(ir), to: outURL.appendingPathComponent("refs.ts"))
        try write(text: emitTypes(ir), to: outURL.appendingPathComponent("types.ts"))
        try write(text: emitRelations(ir), to: outURL.appendingPathComponent("relations.ts"))
        try write(text: emitPolicies(ir), to: outURL.appendingPathComponent("policies.ts"))
        try write(text: emitStateMachines(ir), to: outURL.appendingPathComponent("state-machines.ts"))
        try write(text: emitProtocols(ir), to: outURL.appendingPathComponent("protocols.ts"))
        try write(text: emitSchemas(ir), to: outURL.appendingPathComponent("schemas.ts"))
        try write(text: emitRegistry(ir), to: outURL.appendingPathComponent("registry.ts"))
        try write(text: emitValidators(ir), to: outURL.appendingPathComponent("validators.ts"))
    }

    func emitRefs(_ ir: JSONObject) -> String {
        let classes = ir["classes"] as? [JSONObject] ?? []
        let relations = ir["relations"] as? [JSONObject] ?? []
        let policies = ir["policies"] as? [JSONObject] ?? []
        let stateMachines = ir["stateMachines"] as? [JSONObject] ?? []

        let classRefs = classes.mapValuesById { refLiteral(ir: ir, item: $0, kindKey: "kind") }
        let relationRefs = relations.mapValuesById { refLiteral(ir: ir, item: $0, fixedKind: "Relation") }
        let policyRefs = policies.mapValuesById { refLiteral(ir: ir, item: $0, fixedKind: "Policy") }
        let stateMachineRefs = stateMachines.mapValuesById { refLiteral(ir: ir, item: $0, fixedKind: "StateMachine") }
        var allRefs = JSONObject()
        for source in [classRefs, relationRefs, policyRefs, stateMachineRefs] {
            for key in source.keys.sorted() {
                guard let ref = source[key] as? JSONObject,
                      let alias = ref["alias"] as? String
                else { continue }
                allRefs[alias] = ref
            }
        }

        return """
        // Generated by ontologyc. Do not edit manually.

        export type ConceptRef = {
          readonly ontology: string;
          readonly version: string;
          readonly namespace: string;
          readonly concept: string;
          readonly kindOfConcept: string;
          readonly alias: string;
          readonly uri: string;
        };

        export const classes = \(tsObject(classRefs)) as const;
        export const relations = \(tsObject(relationRefs)) as const;
        export const policies = \(tsObject(policyRefs)) as const;
        export const stateMachines = \(tsObject(stateMachineRefs)) as const;
        export const allRefs = \(tsObject(allRefs)) as const;

        """
    }

    func emitTypes(_ ir: JSONObject) -> String {
        let classes = ir["classes"] as? [JSONObject] ?? []
        let localProtocolFqids = Set((ir["protocols"] as? [JSONObject] ?? []).compactMap { string($0["fqid"]) })
        var referencedProtoNames = [String]()
        var importedProtoRefs = [String]()
        var interfaceLines = [String]()
        for item in classes {
            let id = string(item["id"]) ?? "Unknown"
            let fqid = string(item["fqid"]) ?? id
            let implementedRefs = (item["implements"] as? [String])
                ?? ((item["implements"] as? [Any] ?? []).compactMap { $0 as? String })
            let localProtos = implementedRefs
                .filter { localProtocolFqids.contains($0) }
                .compactMap { fqProtocolRef -> String? in
                    let parts = fqProtocolRef.split(separator: ":", maxSplits: 1)
                    return parts.count == 2 ? String(parts[1]) : nil
                }
            for importedRef in implementedRefs where !localProtocolFqids.contains(importedRef) && importedRef.contains(":") {
                if !importedProtoRefs.contains(importedRef) {
                    importedProtoRefs.append(importedRef)
                }
            }
            for proto in localProtos where !referencedProtoNames.contains(proto) {
                referencedProtoNames.append(proto)
            }
            let extendsClause = localProtos.isEmpty ? "" : " extends \(localProtos.joined(separator: ", "))"
            interfaceLines.append("""
            export interface \(id)\(extendsClause) {
              readonly $type: "\(fqid)";
              readonly id?: string;
            }
            """)
        }
        let interfaces = interfaceLines.joined(separator: "\n\n")
        let protoImport = referencedProtoNames.isEmpty
            ? ""
            : "import type { \(referencedProtoNames.sorted().joined(separator: ", ")) } from \"./protocols\";\n\n"
        let importedWarning = importedProtoRefs.isEmpty
            ? ""
            : "// Warning: imported protocol refs are not emitted as local TypeScript interfaces: \(importedProtoRefs.sorted().joined(separator: ", ")).\n\n"
        return """
        // Generated by ontologyc. Do not edit manually.

        \(importedWarning)\(protoImport)export type OntologyEntityId = string;

        \(interfaces)

        """
    }

    func emitProtocols(_ ir: JSONObject) -> String {
        let protocols = ir["protocols"] as? [JSONObject] ?? []
        if protocols.isEmpty {
            return """
            // Generated by ontologyc. Do not edit manually.

            export const protocolDefinitions = [] as const;

            """
        }
        let interfaces = protocols.map { item -> String in
            let id = string(item["id"]) ?? "Unknown"
            let fields = (item["requiredFields"] as? [String]) ?? ((item["requiredFields"] as? [Any] ?? []).compactMap { $0 as? String })
            let fieldLines = fields.map { "  readonly \($0): string;" }.joined(separator: "\n")
            let body = fieldLines.isEmpty ? "" : "\n\(fieldLines)\n"
            return "export interface \(id) {\(body)}"
        }.joined(separator: "\n\n")
        let defs = tsArray(protocols)
        return """
        // Generated by ontologyc. Do not edit manually.

        \(interfaces)

        export const protocolDefinitions = \(defs) as const;

        """
    }

    func emitSchemas(_ ir: JSONObject) -> String {
        let classes = ir["classes"] as? [JSONObject] ?? []
        let schemaDecls = classes.map { item -> String in
            let id = string(item["id"]) ?? "Unknown"
            let fqid = string(item["fqid"]) ?? id
            return """
            export const \(id)Schema = z.object({
              $type: z.literal("\(fqid)"),
              id: z.string().optional(),
            });
            """
        }.joined(separator: "\n\n")
        let schemaNames = classes.compactMap { string($0["id"]) }.filter { !$0.isEmpty }
        let unionItems = schemaNames.map { "  \($0)Schema" }.joined(separator: ",\n")
        let anyEntitySchema: String
        if schemaNames.count >= 2 {
            anyEntitySchema = """
            export const AnyOntologyEntitySchema = z.discriminatedUnion("$type", [
            \(unionItems),
            ]);
            """
        } else if let only = schemaNames.first {
            anyEntitySchema = "export const AnyOntologyEntitySchema = \(only)Schema;"
        } else {
            anyEntitySchema = "export const AnyOntologyEntitySchema = z.never();"
        }
        return """
        // Generated by ontologyc. Do not edit manually.
        // Requires: zod@^4

        import { z } from "zod";

        \(schemaDecls)

        \(anyEntitySchema)

        export type AnyOntologyEntity = z.infer<typeof AnyOntologyEntitySchema>;

        """
    }

    func emitRelations(_ ir: JSONObject) -> String {
        let relations = ir["relations"] as? [JSONObject] ?? []
        return """
        // Generated by ontologyc. Do not edit manually.

        export const relationDefinitions = \(tsArray(relations)) as const;

        """
    }

    func emitPolicies(_ ir: JSONObject) -> String {
        let policies = ir["policies"] as? [JSONObject] ?? []
        return """
        // Generated by ontologyc. Do not edit manually.

        export const policyDefinitions = \(tsArray(policies)) as const;

        """
    }

    func emitStateMachines(_ ir: JSONObject) -> String {
        let stateMachines = ir["stateMachines"] as? [JSONObject] ?? []
        return """
        // Generated by ontologyc. Do not edit manually.

        export const stateMachineDefinitions = \(tsArray(stateMachines)) as const;

        """
    }

    func emitRegistry(_ ir: JSONObject) -> String {
        let metadata: JSONObject = [
            "id": ir["id"] ?? "",
            "namespace": ir["namespace"] ?? "",
            "version": ir["version"] ?? "",
            "sourceDigest": ir["sourceDigest"] ?? ""
        ]
        return """
        // Generated by ontologyc. Do not edit manually.

        import { classes, relations, policies, stateMachines } from "./refs";
        import { relationDefinitions } from "./relations";
        import { policyDefinitions } from "./policies";
        import { stateMachineDefinitions } from "./state-machines";
        import { protocolDefinitions } from "./protocols";

        export const ontologyMetadata = \(tsObject(metadata)) as const;

        export const ontologyRegistry = {
          metadata: ontologyMetadata,
          refs: { classes, relations, policies, stateMachines },
          relations: relationDefinitions,
          policies: policyDefinitions,
          stateMachines: stateMachineDefinitions,
          protocols: protocolDefinitions,
        } as const;

        """
    }

    func emitValidators(_ ir: JSONObject) -> String {
        _ = ir["id"]
        return """
        // Generated by ontologyc. Do not edit manually.

        import { allRefs } from "./refs";
        import { AnyOntologyEntity, AnyOntologyEntitySchema } from "./schemas";

        export type KnownOntologyRef = keyof typeof allRefs;

        export function isKnownOntologyRef(value: string): value is KnownOntologyRef {
          return Object.prototype.hasOwnProperty.call(allRefs, value);
        }

        export function assertKnownOntologyRef(value: string): KnownOntologyRef {
          if (isKnownOntologyRef(value)) {
            return value;
          }
          throw new Error(`Unknown ontology reference: ${value}`);
        }

        export function parseOntologyEntity(value: unknown): AnyOntologyEntity {
          return AnyOntologyEntitySchema.parse(value);
        }

        """
    }
}
