import Foundation

extension OntologyCompiler {
    func emit(ir: JSONObject, to outDirectory: String) throws {
        let outURL = URL(fileURLWithPath: outDirectory)
        try FileManager.default.createDirectory(at: outURL, withIntermediateDirectories: true)
        try write(json: ir, to: outURL.appendingPathComponent("ontology.normalized.json"))
        try write(text: emitRefs(ir), to: outURL.appendingPathComponent("refs.ts"))
        try write(text: emitTypes(ir), to: outURL.appendingPathComponent("types.ts"))
        try write(text: emitRelations(ir), to: outURL.appendingPathComponent("relations.ts"))
        try write(text: emitPolicies(ir), to: outURL.appendingPathComponent("policies.ts"))
        try write(text: emitStateMachines(ir), to: outURL.appendingPathComponent("state-machines.ts"))
        try write(text: emitRegistry(ir), to: outURL.appendingPathComponent("registry.ts"))
        try write(text: emitValidators(ir), to: outURL.appendingPathComponent("validators.ts"))
    }

    func emitRefs(_ ir: JSONObject) -> String {
        let classes = ir["classes"] as? [JSONObject] ?? []
        let relations = ir["relations"] as? [JSONObject] ?? []
        let policies = ir["policies"] as? [JSONObject] ?? []
        let stateMachines = ir["stateMachines"] as? [JSONObject] ?? []

        let classRefs = classes.mapValuesById { refLiteral(ir: ir, item: $0, kindKey: "kind") }
        let relationRefs = relations.mapValuesById { refLiteral(ir: ir, item: $0, fixedKind: "Relation") }
        let policyRefs = policies.mapValuesById { refLiteral(ir: ir, item: $0, fixedKind: "Policy") }
        let stateMachineRefs = stateMachines.mapValuesById { refLiteral(ir: ir, item: $0, fixedKind: "StateMachine") }
        var allRefs = JSONObject()
        for source in [classRefs, relationRefs, policyRefs, stateMachineRefs] {
            for key in source.keys.sorted() {
                guard let ref = source[key] as? JSONObject,
                      let alias = ref["alias"] as? String
                else { continue }
                allRefs[alias] = ref
            }
        }

        return """
        // Generated by ontologyc. Do not edit manually.

        export type ConceptRef = {
          readonly ontology: string;
          readonly version: string;
          readonly namespace: string;
          readonly concept: string;
          readonly kindOfConcept: string;
          readonly alias: string;
          readonly uri: string;
        };

        export const classes = \(tsObject(classRefs)) as const;
        export const relations = \(tsObject(relationRefs)) as const;
        export const policies = \(tsObject(policyRefs)) as const;
        export const stateMachines = \(tsObject(stateMachineRefs)) as const;
        export const allRefs = \(tsObject(allRefs)) as const;

        """
    }

    func emitTypes(_ ir: JSONObject) -> String {
        let classes = ir["classes"] as? [JSONObject] ?? []
        let interfaces = classes.map { item -> String in
            let id = string(item["id"]) ?? "Unknown"
            let fqid = string(item["fqid"]) ?? id
            return """
            export interface \(id) {
              readonly $type: "\(fqid)";
              readonly id?: string;
            }
            """
        }.joined(separator: "\n\n")
        return """
        // Generated by ontologyc. Do not edit manually.

        export type OntologyEntityId = string;

        \(interfaces)

        """
    }

    func emitRelations(_ ir: JSONObject) -> String {
        let relations = ir["relations"] as? [JSONObject] ?? []
        return """
        // Generated by ontologyc. Do not edit manually.

        export const relationDefinitions = \(tsArray(relations)) as const;

        """
    }

    func emitPolicies(_ ir: JSONObject) -> String {
        let policies = ir["policies"] as? [JSONObject] ?? []
        return """
        // Generated by ontologyc. Do not edit manually.

        export const policyDefinitions = \(tsArray(policies)) as const;

        """
    }

    func emitStateMachines(_ ir: JSONObject) -> String {
        let stateMachines = ir["stateMachines"] as? [JSONObject] ?? []
        return """
        // Generated by ontologyc. Do not edit manually.

        export const stateMachineDefinitions = \(tsArray(stateMachines)) as const;

        """
    }

    func emitRegistry(_ ir: JSONObject) -> String {
        let metadata: JSONObject = [
            "id": ir["id"] ?? "",
            "namespace": ir["namespace"] ?? "",
            "version": ir["version"] ?? "",
            "sourceDigest": ir["sourceDigest"] ?? ""
        ]
        return """
        // Generated by ontologyc. Do not edit manually.

        import { classes, relations, policies, stateMachines } from "./refs";
        import { relationDefinitions } from "./relations";
        import { policyDefinitions } from "./policies";
        import { stateMachineDefinitions } from "./state-machines";

        export const ontologyMetadata = \(tsObject(metadata)) as const;

        export const ontologyRegistry = {
          metadata: ontologyMetadata,
          refs: { classes, relations, policies, stateMachines },
          relations: relationDefinitions,
          policies: policyDefinitions,
          stateMachines: stateMachineDefinitions,
        } as const;

        """
    }

    func emitValidators(_ ir: JSONObject) -> String {
        _ = ir
        return """
        // Generated by ontologyc. Do not edit manually.

        import { allRefs } from "./refs";

        export type KnownOntologyRef = keyof typeof allRefs;

        export function isKnownOntologyRef(value: string): value is KnownOntologyRef {
          return Object.prototype.hasOwnProperty.call(allRefs, value);
        }

        export function assertKnownOntologyRef(value: string): KnownOntologyRef {
          if (isKnownOntologyRef(value)) {
            return value;
          }
          throw new Error(`Unknown ontology reference: ${value}`);
        }

        """
    }
}
